apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-car-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental-car
      tier: web
  template:
    metadata:
      labels:
        app: rental-car
        tier: web
    spec:
      containers:
      - name: rental-car-web
        image: hadiadjadi/my-go-application
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: secret
        - name: DB_NAME
          value: postres12
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.25"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: rental-car-web
spec:
  type: NodePort
  selector:
    app: rental-car
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000


