version: '3.8'

services:
  web:
    type: web
    env: docker
    buildCommand: go run cmd/main.go cmd/Agency.go cmd/Client.go cmd/Car.go cmd/routes.go -b 0.0.0.0
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_USER
        fromDatabase: true
      - key: DB_PASSWORD
        fromDatabase: true
      - key: DB_NAME
        fromDatabase: true
    ports:
      - port: 3000
        protocol: tcp
  db:
    type: web
    env: docker
    image: postgres:alpine
    buildCommand: docker build -t postgres:alpine .
    startCommand: docker run -p 5432:5432 postgres:alpine
    ports:
      - port: 5432
        protocol: tcp
    envVars:
      - key: POSTGRES_USER
        value: ${DB_USER}
      - key: POSTGRES_PASSWORD
        value: ${DB_PASSWORD}
      - key: POSTGRES_DB
        value: ${DB_NAME}
